/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Lotto } from "./Lotto";
export * as factories from "./factories";
export { Lotto__factory } from "./factories/Lotto__factory";
